StaticData = {}
require "static_data.StaticData_Npc"
require "static_data.StaticData_Track"
require "static_data.StaticData_Task"
require "static_data.StaticData_Plot"
require "static_data.StaticData_PlotSection"
require "static_data.StaticData_Shops"
require "static_data.StaticData_Icon"
require "static_data.StaticData_WorldMap"
require "static_data.StaticData_TownMap"
require "static_data.StaticData_TownInterface"
require "static_data.StaticData_TownRoad"
require "static_data.StaticData_Prize"
require "static_data.StaticData_TransDart"
require "static_data.StaticData_ExploreMap"
require "static_data.StaticData_Map"
require "static_data.StaticData_taskMonsterDialog"
require "static_data.StaticData_Item"
require "static_data.StaticData_Level"
require "static_data.StaticData_SystemParam"
require "static_data.StaticData_SelectRoleData"
require "static_data.StaticData_PlatformCode"
require "static_data.StaticData_SelectServer"
return StaticData

